name: Node.js Package

on:
  release:
    types: [published]
jobs:
  publish-npm:
    runs-on: ubuntu-latest
    name: 'Publish new release'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
          registry-url: https://registry.npmjs.org/
      - run: npm install
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
